# Description of samples
samples: samples.tsv
# Description of sequencing units (libraries, resequencing, ...)
units: units.tsv

# Default path for generated files
out_dir: out
tmp_dir: tmp

# Mitochondrial genome from previous assembly
mitochondrion: assets/Acastellanii_neff_mitochontrion_NC_001637.1.fasta

n_cpus: 32

# Software default parameters
params:
  bowtie2: "--sensitive-local"
