# Description of samples
samples  : samples.tsv
# Description of sequencing units (libraries, resequencing, ...)
units    : units.tsv

# Default path for generated files
out_dir  : out
tmp_dir  : tmp

n_cpus   : 32

# Software default parameters
params:
    bowtie2       : "--sensitive-local"
    racon_wrapper : "--subsample 45000000 100 -u"
    pilon         : "--diploid"
