# Description of samples
samples  : samples.tsv
# Description of sequencing units (libraries, resequencing, ...)
units    : units.tsv

# Default path for generated files
out_dir  : out
tmp_dir  : tmp

n_cpus   : 32

remote:
  provider   : "GS"
  bucket     : "test_assembly"
  host       : "tars.pasteur.fr"
  username   : "cmatthey"
  ssh_key    : "/home/cmatthey/.ssh/tars_rsa"
  password   : ""

# Software default parameters
params:
    bowtie2       : "--sensitive-local"
    racon_wrapper : "--subsample 45000000 100 -u"
    pilon         : "--diploid"
