$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
    samples:
        type: string
    units:
        type: string
    out_dir:
        type: string
    tmp_dir:
        type: string
    params:
        type: object
        properties:
            bowtie2:
                type: string
        required:
            - bowtie2
